spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_category_service
    username: root
    password: root


#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: validate

  liquibase:
    change-log: classpath:/db/changelog/migration.xml

jwt:
  secret: k205j@dkjf0%^@
  expiration: 330000


#server:
#  servlet:
#    context-path: /api/v1


# Update to base
#  jpa:
#    hibernate:
#      ddl-auto: update